# Button und Light für WW Zirkulation

binary_sensor:
  - platform: gpio
    pin: D3
    name: "3 - Blue Button"
 
output:
  - platform: esp8266_pwm
    id: output_blue
    pin: D4
    name: "4 - Button Light"
 
light:
  - platform: monochromatic
    output: output_blue
    id: blue_led
