binary_sensor:
  - platform: gpio
    name: "3 - Blue Button"
    pin:
      number: D3
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
 
output:
  - platform: esp8266_pwm
    id: output_blue
    pin: D6
 
light:
  - platform: monochromatic
    output: output_blue
    id: blue_led
    name: "4 - Blue Light"
