binary_sensor:
  - platform: gpio
    pin: D3
    name: "3 - Blue Button"
 
output:
  - platform: esp8266_pwm
    id: output_blue
    pin: D6
 
light:
  - platform: monochromatic
    output: output_blue
    id: blue_led
    name: "4 - Blue Light"
