# Button und Light für WW Zirkulation

binary_sensor:
  - platform: gpio
    pin: D4
    name: "Red Button"
 
output:
  - platform: esp8266_pwm
    id: output_blue
    pin: D5
 
light:
  - platform: monochromatic
    output: output_blue
    id: blue_led
