# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/s0tool/tree/main/esphome
# © Huizebruin.nl
#  # ⬇ Enable Home Assistant API ⬇ # 
api:

#------------------------# Temperature & Humidity #------------------------#

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "1 - Temperatur Büro"
      unit_of_measurement: "°C"
    humidity:
      name: "2 - Luftfeuchtigkeit Büro"
      unit_of_measurement: "%"
    # Update intervel in Seconds
    update_interval: 60s
    model: DHT11
