# Temperatur & Luftfeuchtigkeits Sensor

api:

#------------------------# Temperature & Humidity #------------------------#

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "1 - Temperatur"
      unit_of_measurement: "°C"
    humidity:
      name: "2 - Luftfeuchtigkeit"
      unit_of_measurement: "%"
    # Update intervel in Seconds
    update_interval: 60s
    model: DHT11
