api:
  message:
    "API running."
    
sensor:
  - platform: dht
    pin: D5
    temperature:
      name: "4 - Temperatur Waschraum"
      unit_of_measurement: "°C"
    humidity:
      name: "5 - Luftfeuchtigkeit Waschraum"
      unit_of_measurement: "%"
    # Update intervel in Seconds
    update_interval: 60s
    model: DHT11
